# --------------------- #
#    Generation File    #
# --------------------- #

# Other generation files to import. (Example: intensive_apps -> ~/.config/rebos/imports/intensive_apps.toml)
imports = [
    "gaming"
]

# Packages to be installed via Flatpak
[managers.flatpak-verified]
items = [
    "com.github.tchx84.Flatseal",
]

# Unverified flathub apps
[managers.flatpak-unverified]
items = [
    # "com.valvesoftware.Steam"
]
