# Flatpak

add = "flatpak install --user -y flathub #:?"
remove = "flatpak uninstall --user -y flathub #:?"
upgrade = "flatpak upgrade -y"

plural_name = "unverified-flatpaks"

hook_name = "unverified-flatpak"

[config]
many_args = true
