# Flatpak

add = "flatpak install --user -y flathub-verified #:?"
remove = "flatpak uninstall --user -y flathub-verified #:?"
upgrade = "flatpak upgrade -y"

plural_name = "verified-flatpaks"

hook_name = "verified-flatpak"

[config]
many_args = true
