# Flatpak

add = "flatpak install --user --noninteractive #:?"
remove = "flatpak uninstall --user --noninteractive #:?"
upgrade = "flatpak upgrade --noninteractive"

plural_name = "flatpakrefs"

hook_name = "flatpakrefs"

[config]
many_args = true
