# Flatpak

add = "flatpak install --user --noninteractive --or-update flathub #:?"
remove = "flatpak uninstall --user --noninteractive --or-update flathub #:?"
upgrade = "flatpak upgrade --noninteractive"

plural_name = "unverified-flatpaks"

hook_name = "unverified-flatpak"

[config]
many_args = true
