# Flatpak

add = "flatpak install --user --noninteractive --or-update #:?"
remove = "flatpak uninstall --user --noninteractive --or-update #:?"
upgrade = "flatpak upgrade --noninteractive"

plural_name = "flatpakrefs"

hook_name = "flatpakrefs"

[config]
many_args = true
